# Generated by Django 3.1 on 2020-08-14 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartTwo', '0002_auto_20200813_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneextension',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_no', to=settings.AUTH_USER_MODEL),
        ),
    ]
