# Generated by Django 3.1 on 2020-08-14 12:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PartTwo', '0003_auto_20200814_1201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhoneExtension',
            new_name='User',
        ),
    ]
